# Ruff configuration: https://docs.astral.sh/ruff/configuration/
# Rules: https://docs.astral.sh/ruff/rules/
# Settings: https://docs.astral.sh/ruff/settings/

# Same as Black.
indent-width = 4
line-length  = 88


# Enable Pyflakes (F) and pycodestyle (E, W) codes by default.
# Plus, enable isort (I) for import sorting.
# Enable various other useful rule sets.
[lint]
ignore = [
    "E501", # Line too long (handled by formatter)
]
select = [
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "PL",  # Pylint
    "TID", # ruff-specific rules for tidier code
    "ARG", # Unused function arguments
    "PTH", # Use Pathlib
    "RUF", # Ruff-specific rules
]

# Allow autofix for all enabled rules (when `--fix`)
fixable   = [ "ALL" ]
unfixable = [  ]

# Exclude a few common directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "output*",        # Exclude our output directories
    "docs/conf.py",   # Often has different styling
]

    [lint.per-file-ignores]
    "__init__.py" = [ "F401" ] # Allow unused imports in __init__.py

    [lint.pydocstyle]
    convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
